name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version used to create tag"

env:
  COREDNS_VERSION: 1.11.1
  VERSION: ${{ github.event.inputs.version }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout coredns 
        uses: actions/checkout@v4
        with:
          repository: coredns/coredns
          ref: v${{ env.COREDNS_VERSION }}
      - name: Build release binary
        run: |
          set -x -e
          sed -i 's/^cache:cache/k8s_cache:github.com\/delta10\/k8s_cache/' plugin.cfg
          go generate
          go get github.com/delta10/k8s_cache@main
          make -f Makefile.release release -e LINUX_ARCH="amd64 arm64" VERSION=$VERSION
      - name: Build release binary sha256
        run: (cd release; for asset in `ls -A *tgz`; do sha256sum $asset > $asset.sha256; done)
      - name: Create release.md
        run: |
          echo "This is [CoreDNS $COREDNS_VERSION](https://github.com/coredns/coredns/releases/tag/v$COREDNS_VERSION) compiled with k8s_cache $VERSION." > release.md
      - name: Log release info
        run: |
          set -x -e
          git log -1
          echo ${{ env.COREDNS_VERSION }}
          cat release.md
          sha256sum release/*.tgz
      - name: Draft release
        uses: softprops/action-gh-release@v1
        with:
          body_path: release.md
          name: v${{ env.VERSION }}
          tag_name: v${{ env.VERSION }}
          files: |
            release/*.tgz
            release/*.tgz.sha256
          draft: true
